files:
  - '*.md'
  - '*.js'
  - '*.ts'
  - '*.mdx'
  - '*.astro'
links:
  - old: 'https://github.com/iamvikshan/mina'
    new: 'https://github.com/iamvikshan/amina'
githubUrls:
  types:
    - 'all'
ignore:
  - 'https://github.com/Discordjs/discordjs'
  - 'https://github.com/saiteja-madha'
  - 'https://github.com/lavalink-devs/Lavalink'
  - 'https://github.com/Androz2091/discord-invites-tracker'
createPr: true
